### ISSUE TITLE
Shortcut compatibility

### ISSUE THREAD

**Issue by Allebale** [OblivCode/xcloud-presence#1]
Thanks for making this!. Would it be possible to have the program running in the background without needing to have Chrome open? Basically just notifying Discord when it detects Chrome. I'm asking that cause i made a lot of shortcuts for xCloud and i launch them through a game launcher with all the other Game Pass games.

**Comment by OblivCode** [comment]
Aright, I'll see what I can do.

**Comment by Allebale** [comment]
Thank you. There seems to be a problem though. ShortcutBuilder.exe is not working (nothing happens when i click on it), do i miss any dependencies?
I cant get the RPC to work either. It worked before.

**Comment by OblivCode** [comment]
No dependencies required. I've rebuilt the executable, try it again
